import React, { useState, useEffect } from "react";
import {
  Sun, Moon, Bell, Search, ChevronDown, Users, Share2, Shield,
  ArrowRight, Zap, FileText, Send, Paperclip, Smile, MoreHorizontal,
  Hash, Settings, BarChart2, Flag, User, LogOut, Plus, ChevronRight,
  Calendar, Download, TrendingUp, AlertTriangle, CheckCircle, Lock,
  Mail, Eye, EyeOff, Bot, GraduationCap, Home, MessageCircle,
  FolderOpen, Reply, Ban, Check, Star, Clock, Pencil,
} from "lucide-react";

type Page = "home" | "login" | "register" | "dashboard" | "chat" | "admin";

// ── Data ─────────────────────────────────────────────────────────────────────

const communities = [
  { id: 1, name: "Computer Science 2026", members: 342, icon: "💻", grad: "from-sky-400 to-blue-600", activity: "2 min ago" },
  { id: 2, name: "Mathematics Forum", members: 218, icon: "📐", grad: "from-violet-400 to-purple-600", activity: "15 min ago" },
  { id: 3, name: "Physics & Astronomy", members: 156, icon: "🔭", grad: "from-emerald-400 to-teal-600", activity: "1 hr ago" },
  { id: 4, name: "Business & Economics", members: 289, icon: "📊", grad: "from-amber-400 to-orange-500", activity: "30 min ago" },
  { id: 5, name: "Design & Creative Arts", members: 174, icon: "🎨", grad: "from-rose-400 to-pink-600", activity: "5 min ago" },
];

const dms = [
  { id: 1, name: "Meera Patel", init: "MP", msg: "Hey! Can you share the ML notes?", time: "2:34 PM", unread: 2, color: "bg-violet-500" },
  { id: 2, name: "Rohan Kumar", init: "RK", msg: "Great presentation today 👏", time: "1:15 PM", unread: 0, color: "bg-sky-500" },
  { id: 3, name: "Priya Sharma", init: "PS", msg: "Study session tomorrow at 4?", time: "11:22 AM", unread: 1, color: "bg-emerald-500" },
  { id: 4, name: "Arjun Mehta", init: "AM", msg: "The assignment deadline moved!", time: "10:05 AM", unread: 0, color: "bg-amber-500" },
];

function cx(...args: (string | false | undefined | null)[]) {
  return args.filter(Boolean).join(" ");
}

export function FigmaShowcasePage() {
  const [page, setPage] = useState<Page>("home");
  const [dark, setDark] = useState(false);

  useEffect(() => {
    document.documentElement.classList.toggle("dark", dark);
  }, [dark]);

  const tog = () => setDark((d) => !d);

  return (
    <div style={{ fontFamily: "'Inter', sans-serif" }} className="min-h-screen bg-background">
      {/* Switcher Header Bar for Testing */}
      <div className="bg-slate-900 text-white text-xs px-4 py-2 flex items-center justify-between z-50 sticky top-0 shadow-md">
        <span className="font-bold flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
          Figma UI Interactive Showcase (Exported Prototype)
        </span>
        <div className="flex items-center gap-2">
          {(["home", "login", "register", "dashboard", "chat", "admin"] as const).map((pg) => (
            <button
              key={pg}
              onClick={() => setPage(pg)}
              className={cx(
                "px-2.5 py-1 rounded text-[11px] font-bold uppercase transition-all",
                page === pg ? "bg-sky-400 text-white" : "bg-slate-800 text-slate-300 hover:bg-slate-700"
              )}
            >
              {pg}
            </button>
          ))}
        </div>
      </div>

      <div className="p-8 max-w-6xl mx-auto space-y-6">
        <div className="p-6 rounded-2xl bg-gradient-to-r from-sky-400/20 via-violet-400/20 to-emerald-400/20 border border-sky-400/30">
          <h1 className="text-3xl font-black text-foreground mb-2">Figma UI Screen View: {page.toUpperCase()}</h1>
          <p className="text-sm text-muted-foreground">This interactive showcase switches between all screens generated by Figma.</p>
        </div>
      </div>
    </div>
  );
}
