export const NOTIFICATION_TYPES = {
  COMMUNITY_JOIN: "COMMUNITY_JOIN",
  COMMUNITY_INVITE: "COMMUNITY_INVITE",
  COMMUNITY_UPDATE: "COMMUNITY_UPDATE",
  NEW_MESSAGE: "NEW_MESSAGE",
  DIRECT_MESSAGE: "DIRECT_MESSAGE",
  RESOURCE_UPLOAD: "RESOURCE_UPLOAD",
  MENTION: "MENTION",
  ADMIN_ALERT: "ADMIN_ALERT",
  SYSTEM: "SYSTEM"
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];

export const ENTITY_TYPES = {
  USER: "USER",
  COMMUNITY: "COMMUNITY",
  MESSAGE: "MESSAGE",
  RESOURCE: "RESOURCE",
  REPORT: "REPORT"
} as const;

export type EntityType = (typeof ENTITY_TYPES)[keyof typeof ENTITY_TYPES];
